config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

 
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]do
    member do
      get :followings
      get :followers
    end
  end  
  
  resources :books, only: [:show, :new]
  resources :relationships, only: [:create, :destroy]
  
  resources :favorites, only: [:create, :destroy]

get 'rankings/favorite', to: 'rankings#favorite'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :code, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :book_url, presence: true, length: { maximum: 255 }
  
  has_many :favorites
  has_many :users, through: :favorites

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  def self.ranking
    self.group(:book_id).order('count_book_id DESC').limit(10).count(:book_id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites
  has_many :books, through: :favorites
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def favorite(book)
    self.favorites.find_or_create_by(book_id: book.id)
  end
  
  def unfavorite(book)
    like = self.favorites.find_or_create_by(book_id: book.id)
    like.destroy if like
  end
  
  def favorite?(book)
    self.books.include?(book)
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
   include SessionsHelper
   
  def counts(user)
    @count_followings = user.followings.count
    @count_followers = user.followers.count
  end
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def read(result)
    code = result['isbn']
    name = result['title']
    url = result['itemUrl']
    book_url = result['mediumImageUrl']

    {
      code: code,
      name: name,
      url: url,
      book_url: book_url,
    }
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_user_logged_in
  def show
    @book = Book.find(params[:id])
    @users = @book.users
  end
  
  def new
    @books = []

    @title = params[:title]
    if @title.present?
      results = RakutenWebService::Books::Book.search({
        title: @title,
        imageFlag: 1,
        hits: 20,
      })

      results.each do |result|
        book = Book.find_or_initialize_by(read(result))
        @books << book
      end
    end
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find_or_initialize_by(code: params[:book_code])

    unless @book.persisted?

      results = RakutenWebService::Books::Book.search(isbn: @book.code)

      @book = Book.new(read(results.first))
      @book.save
    end


    current_user.favorite(@book)
    flash[:success] = '本をお気に入りしました。'


    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])

    current_user.unfavorite(@book) 
    flash[:success] = '本のお気に入りを解除しました。'

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def favorite
    @ranking_counts = Favorite.ranking
    @books = Book.find(@ranking_counts.keys)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in

  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをフォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォローを解除しました。'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @books = Book.order('updated_at DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]  

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @count = @user.books.count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/books/_books.html.erb
<% if books.present? %>
  <div class="row">
    <% books.each do |book| %>
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= book.book_url %>" alt="" >
            </div>
            <div class="panel-body">
               <% if book.persisted? %>
                 <p class="item-title"><%= link_to book.name, book %></p>
               <% else %>
                 <p class="item-title"><%= book.name.truncate(50).gsub("　", " ") %></p>
               <% end %>
                  <div class="buttons text-center">
                    <% if logged_in? %>
                      <%= render 'books/favorite_button', book: book %>
                    <% end %>
                  </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/_favorite_button.html.erb
<% if current_user.favorite?(book) %>
  <%= form_tag(favorite_path(book.id), method: :delete) do %>
    <%= hidden_field_tag :book_id, book.id %>
    <%= submit_tag 'Unfavorite', class: 'btn btn-success' %>
  <% end %>
<% else %>
  <%= form_tag(favorites_path) do %>
    <%= hidden_field_tag :book_code, book.code %>
    <%= submit_tag 'favorite', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/books/new.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(new_book_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :title, @title, class: 'form-control input-lg', placeholder: "titleを入力", size: 40 %>
        </div>
        <%= submit_tag '本を検索', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'books', books: @books %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-3 col-sm-6 col-xs-12 col-md-offset-3">
    <div class="item">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          <img src="<%= @book.book_url %>" alt="">
        </div>
        <div class="panel-body">
          <p class="item-title"><%= @book.name %></p>
          <div class="buttons text-center">
            <%= render 'books/favorite_button', book: @book %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="users">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          Favoriteしたユーザ
        </div>
        <div class="panel-body">
          <% @users.each do |user| %>
            <%= link_to user.name, user_path(user) %>
          <% end %>
        </div>
      </div>
    </div>
    
    <p class="text-center"><%= link_to '楽天詳細ページ', @book.url, target: '_blank' %></p>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Bookshelf</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li>
              <%= link_to new_book_path do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                本を探す
              <% end %>
              </li>
            <li><%= link_to 'Favoriteランキング', rankings_favorite_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Microposts</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/rankings/favorite.html.erb
<h1>Favoriteランキング</h1>
<% if @books.present? %>
  <div class="row">
    <% @books.each_with_index do |book, index| %>
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= book.book_url %>" alt="" >
            </div>
            <div class="panel-body">
              <div class="buttons text-center">
                <% if logged_in? %>
                  <%= render 'books/favorite_button', book: book %>
                <% end %>
              </div>
            </div>
            <div class="panel-footer">
              <p class="text-center"><%= index+1 %>位: <%= @ranking_counts[book.id] %> Favorites</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  
  <%= render 'books/books', books: @books %>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>本棚をつくろう</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Favorites <span class="badge"><%= @count %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Favorites <span class="badge"><%= @count %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li><a href="#">Mybooks</a></li>
      <li><a href="#">Followings</a></li>
      <li><a href="#">Followers</a></li>
    </ul>
  </div>
</div>